### ISSUE TITLE
License change 

### ISSUE THREAD

**Issue by mistic** [strongloop/strong-log-transformer#5]
@rmg @sam-github Thanks for the contributions on this module. Do you think it's possible to change the license of this module to `MIT` or something close to that?

**Comment by sam-github** [comment]
I don't know what it would take to change this, probably lots of interactions with the legal dept.

The artistic is a common and very liberal open source license, not sure why your legal doesn't like it.

Are you using it directly? If so, finding an alternative module may be the easiest path.

If you are using it as a dependency of a higher level IBM/Strongloop tool, and this specific dep is a license problem, we may have leverage to convince IBM legal to harmonize its license. Is this the case?

It is odd that this is Artistic, but Loopback is MIT. I can't remember the rationale for that.

@rmg, do you?

**Comment by rmg** [comment]
The rationale was the same (I presume) as npm's rationale - protecting the brand by requiring forks to use a different name.

From a package publishing perspective, it's redundant since npm would require you to publish it under a different name anyway.

@mistic can you say more about how you want to use it and how the Artistic license interferes with that? Maybe we can figure out a simple solution.

**Comment by rmg** [comment]
@mistic the license has been changed to Apache 2.0, along with some other semver-major packaging changes (not API) in #6 and v2.0.0 has been published.

**Comment by mistic** [comment]
@rmg thanks for the quick follow up on this @rmg !
